### ISSUE TITLE
Basic :  "TypeError: value is out of bounds"

### ISSUE THREAD

**Issue by kevincannon** [MariusRumpf/node-lifx#10]
Trying to get a basic hello world example running, but no joy.

I created a new project, imported the node module, and then created a file with just this in it:

```
var LifxClient = require('node-lifx').Client;
var client = new LifxClient();

client.init();
```

Here's the error that's showing up:

```
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt8 (buffer.js:715:5)
    at Object.Packet.headerToBuffer (/Users/kevin.cannon/Documents/node-lifx-helloworld/node_modules/node-lifx/lib/lifx/packet.js:209:7)
    at Object.Packet.toBuffer (/Users/kevin.cannon/Documents/node-lifx-helloworld/node_modules/node-lifx/lib/lifx/packet.js:257:21)
    at Client.<anonymous> (/Users/kevin.cannon/Documents/node-lifx-helloworld/node_modules/node-lifx/lib/lifx/client.js:233:26)
    at /Users/kevin.cannon/Documents/node-lifx-helloworld/node_modules/node-lifx/node_modules/lodash/index.js:2874:23
    at /Users/kevin.cannon/Documents/node-lifx-helloworld/node_modules/node-lifx/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/Users/kevin.cannon/Documents/node-lifx-helloworld/node_modules/node-lifx/node_modules/lodash/index.js:3346:13)
    at Client.send (/Users/kevin.cannon/Documents/node-lifx-helloworld/node_modules/node-lifx/lib/lifx/client.js:223:5)
```
I reckon it's something small. Any tips would be appreciated.

Zip file uploaded here:
https://dl.dropboxusercontent.com/u/89613/node-lifx-helloworld.zip
Any ideas?

**Comment by MariusRumpf** [comment]
Try again with v0.1.1.

**Comment by kevincannon** [comment]
Hey - working perfectly now! Thanks!
