### ISSUE TITLE
Library Randomly Crash

### ISSUE THREAD

**Issue by GreenyDev** [MariusRumpf/node-lifx#33]
Hey there!

I have two LIFx Color 1000 bulbs (one in my bedroom and other in the living room) and a Raspberry Pi that I am running homebridge on. I haven't been able to reproduce consistently (hence randomly :p) but every now and again `homebridge-lifx-lan` (the developer of that plugin sent me here :p) crashes homebridge. I have a feeling however, that the issue is with the two bulbs - the power to the living room light was turned off all day and homebridge hadn't crashed at all until that light came back on. This is the error that is thrown when the crash occurs:
```
buffer.js:830
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:830:11)
    at Buffer.readUInt16LE (buffer.js:876:5)
    at Object.Packet.headerToObject (/usr/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/packet.js:124:18)
    at Object.Packet.toObject (/usr/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/packet.js:141:14)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:161:18)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:540:8)
```
If you need anything else from me, I'll gladly help!

**Comment by MariusRumpf** [comment]
Just merged #29 which will fix it. Will be included in next release.
