### ISSUE TITLE
light.getState(), light.getLabel(), light.getHardwareVersion, ... , time out

### ISSUE THREAD

**Issue by RobinBol** [MariusRumpf/node-lifx#58]
Using the example, the getState() and getHardwareVersion() time out, this used to work. Am I the only one experiencing this issue?

```
Keys:
Press 1 to turn the lights on
Press 2 to turn the lights off
Press 3 to turn the lights red
Press 4 to turn the lights green
Press 5 to turn the lights blue
Press 6 to turn the lights a bright bluish white
Press 7 to turn the lights a bright reddish white
Press 8 to show debug messages including network traffic
Press 9 to hide debug messages including network traffic
Press 0 to exit

Started LIFX listening on 0.0.0.0:56700

New light found.
ID: d073d501c21b
IP: 192.168.1.16:56700
[Error: No LIFX response in time]
/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/example/example.js:14
                console.log('Label: ' + info.label);
                                            ^

TypeError: Cannot read property 'label' of null
    at /Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/example/example.js:14:31
    at Client.<anonymous> (/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/lib/lifx/light.js:127:14)
    at Client.<anonymous> (/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/lib/lifx/client.js:369:24)
    at Array.forEach (native)
    at Client.processMessageHandlers (/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/lib/lifx/client.js:340:24)
    at Client.<anonymous> (/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/lib/lifx/client.js:177:12)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)
```

**Comment by ristomatti** [comment]
I just tried and I got the same error. I tried running the script with the call to `getHardwareVersion` commented out after which the script run without issues. Curiously I then tried running it again with `getHardwareVersion´ and then I had no issues and all lights returned the hardware info also.

I haven't experienced this earlier either so it's likely related to some of the recent firmware updates. One reason could be that the lights aren't responding as fast. Could you try a longer response timeout setting on the client if you still get the same error? Just change line 44 of `interactive-cli.js` to for example:

```javascript
client.init({ messageHandlerTimeout: 90000 });
```

If this doesn't help then it could help wrapping the `getHardwareVersion` to a try catch block and retry a few times.

**Comment by RobinBol** [comment]
I changed the `interative-cli.js` to this:

```
client.on('light-new', function(light) {
	console.log('New light found.');
	console.log('ID: ' + light.id);
	console.log('IP: ' + light.address + ':' + light.port);

	light.getState( (err, info) => {
		if (err) {
			console.log('1', err);
			light.getState( (err, info) => {
				if (err) {
					console.log('2', err);
					light.getState( (err, info) => {
						if (err) {
							console.log('3', err);
							throw err;
						} else {
							console.log('Label: ' + info.label);
							console.log('Power:', (info.power === 1) ? 'on' : 'off');
							console.log('Color:', info.color);
						}
					});
				} else {
					console.log('Label: ' + info.label);
					console.log('Power:', (info.power === 1) ? 'on' : 'off');
					console.log('Color:', info.color);
				}
			});
		} else {
			console.log('Label: ' + info.label);
			console.log('Power:', (info.power === 1) ? 'on' : 'off');
			console.log('Color:', info.color);
		}
	});
});
```

Which results in this:
```
Keys:
Press 1 to turn the lights on
Press 2 to turn the lights off
Press 3 to turn the lights red
Press 4 to turn the lights green
Press 5 to turn the lights blue
Press 6 to turn the lights a bright bluish white
Press 7 to turn the lights a bright reddish white
Press 8 to show debug messages including network traffic
Press 9 to hide debug messages including network traffic
Press 0 to exit

Started LIFX listening on 0.0.0.0:56700

New light found.
ID: d073d501c21b
IP: 192.168.1.16:56700
1 [Error: No LIFX response in time]
2 [Error: No LIFX response in time]
3 [Error: No LIFX response in time]
/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/example/example.js:20
                                                        throw err;
                                                        ^

Error: No LIFX response in time
    at Client.<anonymous> (/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/lib/lifx/client.js:368:19)
    at Array.forEach (native)
    at Client.processMessageHandlers (/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/lib/lifx/client.js:340:24)
    at Client.<anonymous> (/Users/robinbolscher/Development/apps/com.lifx/node_modules/node-lifx/lib/lifx/client.js:177:12)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)
```

Strange thing is, I noticed it did succeed one time to fetch the state form the bulb, but about 9/10 times it fails.

**Comment by Sawtaytoes** [comment]
I would say there might be something wrong with your network if 9/10 times it fails. Are you running node-lifx off WiFi?

For me, it's more like 1/100 times it fails, but I'm running off Ethernet.
